<nav>
            <div class="logo">
                <h4>PhoneShop</h4>
            </div>
            <ul class="nav_link">
                <li>
                    <a href="#">HOME</a>
                </li>
                <li >
                    <a href="#">CATEGORY</a>
                </li>
                <li >
                    <a href="#">BLOG</a>
                </li>
                <li >
                    <a href="#">CONTACT</a>
                </li>
            </ul>
            <div class="font-icon">
                <div>
                <a href="#"><i class="ti-user"></i></a>
                </div>
                <div>
                <a href="#"><i class="ti-search"></i></a> 
                </div>
                <div>
                <a href="#"><i class="ti-shopping-cart"></i></a>
                </div>
            </div>
            <div class="burger">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
        </nav>
        